var question = {
    XMZ:[{
        questionIndex:1,
        title:'每周有效项目工作时间（可包括项目学习时间）是多少？（20）',
        options:[
            {
                optionIndex:1,
                content:'每周有效工作时间为40小时及以上',
                score:20
            },
            {
                optionIndex:2,
                content:'每周有效工作时间为30-39小时',
                score:15
            },
            {
                optionIndex:3,
                content:'每周有效工作时间为20-29小时',
                score:10
            },
            {
                optionIndex:4,
                content:'每周有效工作时间为10-19小时',
                score:5
            },
            {
                optionIndex:5,
                content:'每周有效工作时间为低于10小时',
                score:0
            },
        ]
    },
        {
            questionIndex:2,
            title:'本职工作完成的时效性和质量情况怎么样？（20）',
            options:[
                {
                    optionIndex:1,
                    content:'经常提前完成任务，且质量很高',
                    score:20
                },
                {
                    optionIndex:2,
                    content:'能够按时完成任务，且质量较高',
                    score:15
                },
                {
                    optionIndex:3,
                    content:'基本上能按时完成任务，且质量达到要求',
                    score:10
                },
                {
                    optionIndex:4,
                    content:'基本按时完成任务，但完成质量不高',
                    score:5
                },
                {
                    optionIndex:5,
                    content:'经常不能按时完成任务，且质量不高',
                    score:0
                },
            ]
        },
        {
            questionIndex:3,
            title:'发现和承担项目额外工作的主动性如何？（10）',
            options:[
                {
                    optionIndex:1,
                    content:'经常主动积极发现并承担任务或者帮助他人',
                    score:10
                },
                {
                    optionIndex:2,
                    content:'完成本职工作后，项目组给出额外任务时会主动承担，但没有主动挖掘其他任务',
                    score:8
                },
                {
                    optionIndex:3,
                    content:'完成本职工作，有时承担额外分配的工作，但不够主动',
                    score:5
                },
                {
                    optionIndex:4,
                    content:'会完成本职工作，没有承担过额外工作',
                    score:3
                },
                {
                    optionIndex:5,
                    content:'不能主动完成本职工作',
                    score:0
                },
            ]
        },
        {
            questionIndex:4,
            title:'对份内工作的负责程度；对他人求助工作的负责程度如何？（10）',
            options:[
                {
                    optionIndex:1,
                    content:'对工作认真负责，经常与各方面及时交流并提出改善建议',
                    score:10
                },
                {
                    optionIndex:2,
                    content:'对本职工作认真负责，对于他人求助工作也会认真负责',
                    score:8
                },
                {
                    optionIndex:3,
                    content:'对本职工作认真负责，对于他人求助工作只是一般应付',
                    score:5
                },
                {
                    optionIndex:4,
                    content:'对本职工作认真负责，对他人求助的工作不认真或者不愿意予以帮助',
                    score:3
                },
                {
                    optionIndex:5,
                    content:'对本职工作不能认真负责',
                    score:0
                },
            ]
        },
        {
            questionIndex:5,
            title:'对我的影响程度（包括正面、负面影响）?（10）',
            options:[
                {
                    optionIndex:1,
                    content:'在为人处事、技术学习各方面一直激励着我',
                    score:10
                },
                {
                    optionIndex:2,
                    content:'在为人或技术等其中一方面激励着我',
                    score:8
                },
                {
                    optionIndex:3,
                    content:'对我既有积极影响也有消极影响，但积极大于消极',
                    score:5
                },
                {
                    optionIndex:4,
                    content:'对我没有任何影响',
                    score:3
                },
                {
                    optionIndex:5,
                    content:'对我的消极影响大于积极影响',
                    score:0
                },
            ]
        },
        {
            questionIndex:6,
            title:'项目组内各种文化活动的组织、参与和支持情况?(5)',
            options:[
                {
                    optionIndex:1,
                    content:'经常主动请求活动组织任务，对文化建设有较大贡献',
                    score:5
                },
                {
                    optionIndex:2,
                    content:'分配的活动任务会认真完成，但不主动申请',
                    score:4
                },
                {
                    optionIndex:3,
                    content:'从未参加活动组织工作，但经常积极参与',
                    score:3
                },
                {
                    optionIndex:4,
                    content:'很少参与集体文化活动或者分配的活动任务不会认真完成',
                    score:1
                },
                {
                    optionIndex:5,
                    content:'从来没有参与集体文化活动',
                    score:0
                },
            ]
        },
        {
            questionIndex:7,
            title:'额外提供技术培训、技术辅助工具等贡献情况?(5)',
            options:[
                {
                    optionIndex:1,
                    content:'会克服各种困难主动提供有用额外技术，即便超出能力范围',
                    score:5
                },
                {
                    optionIndex:2,
                    content:'会在能力范围内主动积极地为项目组提供有用额外技术',
                    score:4
                },
                {
                    optionIndex:3,
                    content:'在大家的邀请下会提供额外技术帮助，自己不会主动提出',
                    score:3
                },
                {
                    optionIndex:4,
                    content:'没有作何额外技术贡献',
                    score:2
                },
                {
                    optionIndex:5,
                    content:'即便他人邀请，也没有提供能力范围内的额外技术贡献',
                    score:0
                },
            ]
        },
    ],
    DWH:[{
        questionIndex:1,
        title:'有效的时间投入（4）',
        options:[
            {
                optionIndex:1,
                content:'非常多',
                score:4
            },
            {
                optionIndex:2,
                content:'较多',
                score:3
            },
            {
                optionIndex:3,
                content:'一般',
                score:2
            },
            {
                optionIndex:4,
                content:'非常少',
                score:0
            }
        ]
    },{
        questionIndex:2,
        title:'任务完成质量（4）',
        options:[
            {
                optionIndex:1,
                content:'非常高',
                score:4
            },
            {
                optionIndex:2,
                content:'较高',
                score:3
            },
            {
                optionIndex:3,
                content:'一般',
                score:2
            },
            {
                optionIndex:4,
                content:'较差',
                score:0
            }
        ]
    },{
        questionIndex:3,
        title:'任务完成效率（4）',
        options:[
            {
                optionIndex:1,
                content:'非常高',
                score:4
            },
            {
                optionIndex:2,
                content:'较高',
                score:3
            },
            {
                optionIndex:3,
                content:'一般',
                score:2
            },
            {
                optionIndex:4,
                content:'较低',
                score:0
            }
        ]
    },{
        questionIndex:4,
        title:'积极主动性（4）',
        options:[
            {
                optionIndex:1,
                content:'非常高',
                score:4
            },
            {
                optionIndex:2,
                content:'较高',
                score:3
            },
            {
                optionIndex:3,
                content:'一般',
                score:2
            },
            {
                optionIndex:4,
                content:'较低',
                score:0
            }
        ]
    },{
        questionIndex:5,
        title:'对自己的影响力（4）',
        options:[
            {
                optionIndex:1,
                content:'有较大的正面影响',
                score:4
            },
            {
                optionIndex:2,
                content:'有正面影响，但不大',
                score:3
            },
            {
                optionIndex:3,
                content:'没有影响',
                score:2
            },
            {
                optionIndex:4,
                content:'有负面影响',
                score:0
            }
        ]
    },],
    ZZB:[{
        questionIndex:1,
        title:'课堂纪律和课堂活跃程度（20）',
        options:[
            {
                optionIndex:1,
                content:'严格遵守课堂纪律，发言积极',
                score:20
            },
            {
                optionIndex:2,
                content:'基本遵守课堂纪律，发言积极',
                score:15
            },
            {
                optionIndex:3,
                content:'基本遵守课堂纪律，发言较积极',
                score:10
            },
            {
                optionIndex:4,
                content:'基本遵守课堂纪律，但发言不积极',
                score:5
            },
            {
                optionIndex:5,
                content:'无故旷课，经常缺交或迟交作业',
                score:0
            }
        ]
    },
        {
            questionIndex:2,
            title:'实验或课程设计的投入、质量、进步速度及合作精神（20）',
            options:[
                {
                    optionIndex:1,
                    content:'投入多，质量高，进步速度快，合作精神强',
                    score:20
                },
                {
                    optionIndex:2,
                    content:'投入多，进步速度快，合作精神强，但质量一般',
                    score:15
                },
                {
                    optionIndex:3,
                    content:'个人能力较强，但合作精神不够',
                    score:10
                },
                {
                    optionIndex:4,
                    content:'投入一般，质量一般，进步不明显',
                    score:5
                },
                {
                    optionIndex:5,
                    content:'投入少，质量差，合作精神差',
                    score:0
                }
            ]
        },
        {
            questionIndex:3,
            title:'关心和承担班级工作的主动程度（10）',
            options:[
                {
                    optionIndex:1,
                    content:'经常主动积极发现并承担班级工作或者帮助他人',
                    score:10
                },
                {
                    optionIndex:2,
                    content:'完成布置工作后，不会去挖掘班级上其他工作，但有任务就会主动承担',
                    score:8
                },
                {
                    optionIndex:3,
                    content:'完成布置工作，有时承担额外分配的工作，但不够主动',
                    score:5
                },
                {
                    optionIndex:4,
                    content:'会完成布置工作，没有承担过额外工作',
                    score:3
                },
                {
                    optionIndex:5,
                    content:'不能主动完成布置工作',
                    score:0
                }
            ]
        },
        {
            questionIndex:4,
            title:'对布置工作的负责程度；对他人求助的尽心程度（10）',
            options:[
                {
                    optionIndex:1,
                    content:'对工作认真负责，经常与各方面及时交流并提出改善建议',
                    score:10
                },
                {
                    optionIndex:2,
                    content:'对布置工作认真负责，对于他人求助工作也会认真负责',
                    score:8
                },
                {
                    optionIndex:3,
                    content:'对布置工作认真负责，对于他人求助工作只是一般应付',
                    score:5
                },
                {
                    optionIndex:4,
                    content:'对布置工作认真负责，但不会关心留意他人工作',
                    score:3
                },
                {
                    optionIndex:5,
                    content:'对布置工作不能认真负责',
                    score:0
                }
            ]
        },
        {
            questionIndex:5,
            title:'对我的影响程度（包括正面、负面影响）（15）',
            options:[
                {
                    optionIndex:1,
                    content:'在为人处事、技术学习各方面一直激励着我',
                    score:15
                },
                {
                    optionIndex:2,
                    content:'在为人或技术等其中一方面激励着我',
                    score:12
                },
                {
                    optionIndex:3,
                    content:'有时候会激励我，而有时候会有消极影响',
                    score:9
                },
                {
                    optionIndex:4,
                    content:'对我没有任何影响',
                    score:6
                },
                {
                    optionIndex:5,
                    content:'对我只有消极影响',
                    score:0
                }
            ]
        },
        {
            questionIndex:6,
            title:'班级各种文化活动的组织、参与和支持情况（10）',
            options:[
                {
                    optionIndex:1,
                    content:'经常主动请求活动组织任务，对文化建设有较大贡献',
                    score:5
                },
                {
                    optionIndex:2,
                    content:'分配的活动任务会认真完成，但不主动申请',
                    score:4
                },
                {
                    optionIndex:3,
                    content:'从未参加活动组织工作，但经常积极参与',
                    score:3
                },
                {
                    optionIndex:4,
                    content:'很少参与集体文化活动或者分配的活动任务不会认真完成',
                    score:1
                },
                {
                    optionIndex:5,
                    content:'从来没有参与集体文化活动',
                    score:0
                }
            ]
        },
        {
            questionIndex:7,
            title:'为班级争得荣誉和对外辐射力（15）',
            options:[
                {
                    optionIndex:1,
                    content:'为班级争得校级及以上荣誉',
                    score:15
                },
                {
                    optionIndex:2,
                    content:'为班级争得校内的各种荣誉',
                    score:12
                },
                {
                    optionIndex:3,
                    content:'主动对外宣传种子班模式，消除误解',
                    score:9
                },
                {
                    optionIndex:4,
                    content:'对班级荣誉没有任何贡献',
                    score:6
                },
                {
                    optionIndex:5,
                    content:'对班级带来负面影响',
                    score:0
                }
            ]
        },]
}
var groupInfo = {
    XMZ:['norway'],
    DWH:['tech'],
    ZZB:['seed12'],
}

module.exports.question = question;
module.exports.groupInfo = groupInfo;